management:
  info:
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8090
course:
  message: "Hola mundo"
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect